### ISSUE TITLE
new solution for parties

### ISSUE THREAD

**Issue by jamesturk** [opencivicdata/pupa#118]
declaring parties is repetitive & error prone, perhaps it should be part of something like dbinit instead of a per-Jurisdiction thing (this would also have the side effect of solving #117)

what about something like 

```
$ pupa addparty Republican
```

and a better error message when someone tries to use a party that isn't declared?

**Comment by jpmckinney** [comment]
Wouldn't you then need to establish some sort of "super-jurisdiction" in which these parties exist, since at the international level, two Republican parties from two countries aren't the same?

**Comment by jpmckinney** [comment]
Nevermind! I just remembered that parties are already not bound to jurisdictions. Yes, this solution seems fine to me.

**Comment by jamesturk** [comment]
should probably throw this in 0.5 while breaking everything else

**Comment by jamesturk** [comment]
are people OK with this solution?   

to refresh, the bug in #117 necessitates a better solution for parties in the long term- because parties are some of the only items that aren't tied to a jurisdiction, they necessitate special handling of some kind.  

it'll wind up replacing parties in the Jurisdiction __init__.py (which is already sort of incorrect since they aren't tied to Jurisdictions) and will be an extra step in the initial setup (and whenever new parties are added)

**Comment by fgregg** [comment]
I'd like to get @ gordonje's thoughts on this, as he has been up to his eyeballs in related issues for the election components.

**Comment by jamesturk** [comment]
ping @gordonje

**Comment by gordonje** [comment]
This makes sense to me.

Probably worth pointing out here that the draft election spec has a `Party` data type that's a subclass of `Organization` and adds the properties abbreviation, color and is_write_in. Had not occurred to me until just now: Maybe this data type should be part of the core models (not just an elections thing)?

**Comment by jamesturk** [comment]
Hmm, it could be worth looking at.

I haven't kept up w/ the development of the election spec but I wonder
about these, abbreviation might make sense (if we're saying that it isn't
just an alternate name/identifier).


And as for is_write_in, wouldn't the write in status be decided on a
per-election basis instead of being a property of the Party itself? (i.e.
US Green party makes the threshold for inclusion in an election here or
there, but not in most)

And color seems unusual too, can you clarify what it'd mean?

**Comment by jpmckinney** [comment]
Just FYI, the spec was accepted as 'draft' so there's an opportunity to adjust these.

**Comment by gordonje** [comment]
A lot of what went into the elections spec was borrowed from the Voting Information Project's [XML specification](http://vip-specification.readthedocs.io/en/release/xml.html). These three properties were all ported over from VIP's [Party element](http://vip-specification.readthedocs.io/en/release/built_rst/xml/elements/party.html#).

I like abbreviation as it's own property separate from alternate names because, in many cases, you just want to display this shortened version of the name. And it seems good to standardize abbreviations along with the full party names.

You make a good point about the is_write_in potential changing from one election cycle to the next. VIP wouldn't have this problem because it's tailored to model a single election, while we need to model multiple elections, past and future. TBH I was kind of speculating about the utility of this field when I ported from VIP. If folks find it useful but also require means of tracking in which election the party was/wasn't recognized by the jurisdiction...maybe we could use a `date_recognized` field instead?

Color is an optional place of storing the hex-code of the color associated with the party. Seemed general useful, but I don't have strong feelings about keeping it if it's confusing/getting in the way.

**Comment by gordonje** [comment]
A couple of related points regarding party...

In our implementation of the elections spec for California, we've found it necessary to represent a few categories that don't quite fit into the "A party is an organization" paradigm. Specifically:

* "No Party Preference" for candidates who declined to declare a party when declaring candidacy for office.
* "Non-partisan" for candidates in non-partisan office (where the don't declare a political party when declaring candidacy).
* "Unknown Party" for candidates who we know should have a party (or "no party preference") but we haven't extracted this from a our various data sources.

What we're currently doing is adding each of these categories as a `Party` object, which means it's also an `Organization`. It's a little odd, but we need all of these categories for aggregation purposes, and this seems like the path of least resistance.

Don't know that any of this requires any changes to the models. Just wanted to share some knowledge about how this is working in practice.
