### ISSUE TITLE
Add full_text as attribute of bills

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/pupa#197]
For New York City Council, the full text of the legislation is available right on the scraped page: http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=2386636&GUID=97B64CDC-6C69-4BFD-9AF0-42678131EDFE&Options=ID%7cText%7c&Search=

There doesn't seem to be a way to store this text in a bill object except in the `extras` field. What do people think about adding this as optional attribute?

**Comment by fgregg** [comment]
Maybe, the full text could be attached a bill version?

**Comment by rshorey** [comment]
this is a problem in miami-dade too that I haven't gotten around to dealing with yet. @mileswwatkins knows more about how we deal with full text than I do, since he wrote the (not yet merged, I think) code for how we pull text to elasticsearch. @mileswwatkins what do you think is the best way to make OCD robust to inline html bill text?

**Comment by rshorey** [comment]
or is there already a way to deal with this that I don't know about (or have forgotten)

**Comment by jamesturk** [comment]
FWIW I don't think we got to this point w/ OCD, I was moving in the
direction of storing full text on versions/documents and hopefully using
the pg full text stuff to avoid the awkward ElasticSearch dance we do right
now.  Either way, it'd still be possible to use ES to index (using a river
perhaps) if it were stored in PG as well.

It wasn't stored in the DB due to Mongo limitations for OS, but with
Postgres there's really not much of a reason not to (maybe make a dump
without that table included though?)

(had to make a quick reply for now, glad to expound later, sorry for
dropping in)

**Comment by mileswwatkins** [comment]
Thanks for the insight, @jamesturk!

My initial response would be that we could just continue storing only the links to document text, in the same way that we only store the links (and not the actual images) for `people` photos in OCD. But if the fulltext capabilities are good to go in Postgres then I'm absolutely game to build that!

@all, what're your preferences? @paultag, @jpmckinney: any obvious issues we're overlooking?

**Comment by jpmckinney** [comment]
ref: http://docs.opencivicdata.org/en/latest/proposals/0006.html

From what I can tell, Billy didn't store text either. If OCD stores text, it should be on the version/document object, not the bill object.

**Comment by paultag** [comment]
Yeah, document push was something on the TODO. No reason you can't use a PostgreSQL document table and index the crap out of it to do some full text searching

**Comment by mileswwatkins** [comment]
Yeah, @rshorey's right that I have an outstanding PR to handle an Elasticsearch document push to do this fulltext stuff. But I like the sound of Postgres, too.

**Comment by fgregg** [comment]
Agree with @jpmckinney that bill_text should def be stored under the version object.

**Comment by jamesturk** [comment]
going to draft a OCDEP I suppose, but since it is discussed here a bit already, would people be amenable to an (optional) ``text`` attribute on BillDocumentLink/BillVersionLink?

**Comment by fgregg** [comment]
@jamesturk I would

**Comment by fgregg** [comment]
Also, we would need also want to make url optional. In NYC we don't have different urls for different versions of a bill. 

http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=2230883&GUID=4D870FC4-85A9-4228-BCC4-3E8DCBC26326

**Comment by jamesturk** [comment]
A little unclear on the no-URL thing, isn't http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=2230883&GUID=4D870FC4-85A9-4228-BCC4-3E8DCBC26326 a valid URL for that bill text?

**Comment by jamesturk** [comment]
added ``text`` & migration to ocd models and pupa in dev branches, the URL issue is probably worth a separate ticket if needed

**Comment by fgregg** [comment]
The no-url thing -- it's the same url for both versions of the bill. The different versions are loaded through posts request.
