### ISSUE TITLE
Consider start date in addition to, or instead of, end date when importing memberships

### ISSUE THREAD

**Issue by hancush** [opencivicdata/pupa#303]
Hi from DataMade!

Today we encountered a situation where the end date on a membership changed in our data source (Legistar). Because the membership importer checks end date, not start date, the import created a new membership rather than updating the end date on the existing one, ultimately resulting in duplicate memberships in the database.

https://github.com/opencivicdata/pupa/blob/9a09139ce4153f2c40694c4a57ee8b2ef086459d/pupa/importers/memberships.py#L21-L27

Can you say more about the rationale about considering the end date, rather than the start date, to identify a particular membership object? It seems like start date, in combination with the rest of the spec, is just as indicative of specific membership – is this a change you'd be amenable to, if I were to open a PR? 

Thanks for all you do!

**Comment by jamesturk** [comment]
Honestly I'm not 100% sure what the logic was, looking at the comment there it looks like we were thinking dates were only set on historical roles, which probably is the case in 95% of jurisdictions.

If I'm understanding correctly you'd like to take start date into consideration as well (or instead of end_date?)?

I'm not sure if this would really affect any current use so I'm in general in favor if it helps you all out, especially if it can be done in a backwards-compatible way, and if not we can just think through cases that your patch would break and make a decision on how to roll that out appropriately.

**Comment by hancush** [comment]
Resurrecting this issue. This happened again for us. I would expect pupa to register change in end date as an update, rather than a new membership. Maybe [the spec](https://github.com/opencivicdata/pupa/blob/d4b10ac620c6657f69916918585bce65b51eec79/pupa/importers/memberships.py#L27) could use start date by default and fall back to end date if there is not a start date. 

Are you all still using pupa in a way that would make this change relevant, @jamesturk?

**Comment by jamesturk** [comment]
Ah I'm not Open States is no longer using pupa.  pupa is yours to do what you wish with :)

**Comment by hancush** [comment]
Done in #336.
