### ISSUE TITLE
Add a way to de-duplicate `actions` on a `Bill`

### ISSUE THREAD

**Issue by mileswwatkins** [opencivicdata/pupa#307]
Sometimes, `Bill`s can have `actions` that share all [info](https://github.com/opencivicdata/pupa/blob/master/pupa/scrape/bill.py#L47-L54) (ie, both `description` and `date`), and are genuinely different. Pupa currently doesn't allow this, and throws an error on-import of these.

One option would be to add an optional `pupa_id` field, similar to what was added for `VoteEvent`s. This can't be done in, say, `action.extras` right now, since `extras` isn't used when de-duplicating on-import.

**Comment by mileswwatkins** [comment]
Here's a concrete example of this happening: https://github.com/openstates/openstates/pull/2108

**Comment by mileswwatkins** [comment]
See also https://github.com/opencivicdata/python-opencivicdata/issues/114

**Comment by jamesturk** [comment]
So I'm pretty sure pupa has no issue with duplicate actions, the 'order' field is always unique.  https://github.com/opencivicdata/pupa/compare/master...jpt-307 demonstrates that this works (the tests pass)

Looking more closely at this, opencivicdata/python-opencivicdata#114 has the following stacktrace:

```
pupa.exceptions.DataImportError: duplicate key value violates unique constraint "opencivicdata_voteevent_bill_action_id_key"
DETAIL:  Key (bill_action_id)=(0c9194c7-01e3-4c4a-a183-b03f9631c0f0) already exists.
 while importing {'extras': {}, 'organization_id': 'ocd-organization/1cf80fcd-e90e-4d0b-87d6-304fad2262f9', 'bill_id': 'ocd-bill/34a341ef-ce92-4be0-8bc5-baa7840147cf', 'identifier': '', 'result': 'pass', 'motion_classification': ['passage'], 'legislative_session_id': UUID('f7bb567b-bf81-42e3-ac8d-499128c76047'), 'start_date': '2017-02-01', 'motion_text': 'Do Pass', 'bill_action_id': UUID('0c9194c7-01e3-4c4a-a183-b03f9631c0f0')} as 
```

This is because a OneToOne field is used to link one VoteEvent to one BillAction and in this case the same BillAction is being linked to multiple VoteEvents.

(FTR, Multiple BillActions that match would wind up here: https://github.com/opencivicdata/pupa/blob/master/pupa/importers/vote_events.py#L95) but there's no guarantee that no VoteEvent has already matched a given BillAction.

Two possible solutions:
- change the code in pupa.importers.vote_events to check if the action it has pulled back has already been matched to a VoteEvent, and if so, don't create a BillAction linkage
- change the model so that VoteEvent has a ForeignKey to BillAction, thus allowing a BillAction to have multiple associated votes

I don't think that option #2 is actually a OCDEP change (but is a minor schema change), and it does seem like a single action could be referenced by multiple votes so I'm most likely in favor of that but want to think it through.

**Comment by jamesturk** [comment]
actually after looking at the code it makes sense that this is a OneToOne, we even check for this but just didn't handle the addition of pupa_id well (when two votes could have duplicate info) I've added a test and fix for this in PR
